apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skripsi-domain-cert
  namespace: istio-system
spec:
  secretName: skripsi-domain-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "skripsi.lakik.software"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io