apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account-app
        image: asia-southeast1-docker.pkg.dev/skripsi-exploration/skripsi-code/account:latest
        ports:
        - containerPort: 8081
        env:
          - name: PORT
            value: "8081"
---

apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account
  ports:
  - port: 8081
    targetPort: 8081