apiVersion: apps/v1
kind: Deployment
metadata:
  name: rogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rogue
  template:
    metadata:
      labels:
        app: rogue
    spec:
      containers:
      - name: rogue-app
        image: asia-southeast1-docker.pkg.dev/skripsi-exploration/skripsi-repo/rogue:latest
        ports:
        - containerPort: 8082
        env:
          - name: PORT
            value: "8082"
---

apiVersion: v1
kind: Service
metadata:
  name: rogue-service
spec:
  selector:
    app: rogue
  ports:
  - port: 8082
    targetPort: 8082