version: '3'
services:
  account-service:
    container_name: account
    build:
      context: ./account
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8081:8081'
  membership-service:
    container_name: membership
    build:
      context: ./membership
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'