apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-deployment-and-service
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: validate-deployment
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        manifests:
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmnIn28vDRD2e/CvoU1YCNWCOQDB8
                      2GbSGKIcMPEcRtWK1KDWgUv+CGjHobwugRzxaxIfH/3EKxXUWDsTrjm8gQ==
                      -----END PUBLIC KEY-----
    - name: validate-service
      match:
        any:
          - resources:
              kinds:
                - Service
      validate:
        manifests:
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmnIn28vDRD2e/CvoU1YCNWCOQDB8
                      2GbSGKIcMPEcRtWK1KDWgUv+CGjHobwugRzxaxIfH/3EKxXUWDsTrjm8gQ==
                      -----END PUBLIC KEY-----
