apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: account-route
spec:
  http:
    - match:
        - uri:
            exact: /account
      route:
        - destination:
            host: account-service
            port:
              number: 8081
